# Site settings
title: Nathan Brenner
email: nathan.j.brenner@gmail.com
description: A sample of my work and thoughts
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nathan-j-brenner.github.io/" # the base hostname & protocol for your site
twitter_username: njbrenner
github_username:  nathan-j-brenner
# Gems
gems: [jekyll-paginate]
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      author: Nathan
      layout: "post"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
      